### ISSUE TITLE
Ubuntu 16.04 Exception

### ISSUE THREAD

**Issue by tilowr** [jamesdlow/open-airplay#14]
$ java -jar airplay.jar
Exception in thread "main" java.lang.NoClassDefFoundError: javax/jmdns/JmDNS
	at com.jameslow.AirPlay.search(Unknown Source)
	at com.jameslow.AirPlay.search(Unknown Source)
	at com.jameslow.AirPlay.searchDialog(Unknown Source)
	at com.jameslow.AirPlay.searchDialog(Unknown Source)
	at com.jameslow.AirPlay.main(Unknown Source)
Caused by: java.lang.ClassNotFoundException: javax.jmdns.JmDNS
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 5 more

**Comment by johnny-k** [comment]
Hi,
you are missing some external libraries. As stated on the project page you require [JMDNS](https://github.com/jmdns/jmdns/releases), also you need [SLF4J](https://www.slf4j.org/download.html). From SLF4J you need the api and an implementation e.g simple or nop. Then open your command line and write
`java -cp slf4j-api.jar:slf4j-nop.jar:jmdns.jar:airplay.jar com.jameslow.AirPlay`
This solves your issue, but it crashes later after selecting an appleTV and a screen resolution.
