### ISSUE TITLE
Photo Error when I try to cast my screen?

### ISSUE THREAD

**Issue by NullVoxPopuli** [jamesdlow/open-airplay#16]
Here is my command and error:
```
java -jar airplay.jar -h 10.0.100.210 -d
Press ctrl-c to quit
java.io.IOException: Server returned HTTP response code: 453 for URL: http://10.0.100.210:7000/photo
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at sun.net.www.protocol.http.HttpURLConnection$10.run(HttpURLConnection.java:1926)
	at sun.net.www.protocol.http.HttpURLConnection$10.run(HttpURLConnection.java:1921)
	at java.security.AccessController.doPrivileged(Native Method)
	at sun.net.www.protocol.http.HttpURLConnection.getChainedException(HttpURLConnection.java:1920)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1490)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1474)
	at com.jameslow.AirPlay.doHTTP(Unknown Source)
	at com.jameslow.AirPlay.doHTTP(Unknown Source)
	at com.jameslow.AirPlay.photoRaw(Unknown Source)
	at com.jameslow.AirPlay.photoRawCompress(Unknown Source)
	at com.jameslow.AirPlay$PhotoThread.run(Unknown Source)
Caused by: java.io.IOException: Server returned HTTP response code: 453 for URL: http://10.0.100.210:7000/photo
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1876)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1474)
	at java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:480)
	... 5 more
```

I was following this: https://askubuntu.com/questions/833436/airplay-mirroring-from-ubuntu-16-04-to-apple-tv

**Comment by zanferrari** [comment]
Hi,
I think Apple modified something in their last protocol update. Wil be the openAirplay updated in order to work with the last version of apple tv? I use it long time with pleasure.
