### ISSUE TITLE
Can't connect

### ISSUE THREAD

**Issue by jimisan** [jamesdlow/open-airplay#19]
java -jar airplay.jar -h 172.80.255.65 -d
Press ctrl-c to quit
java.io.IOException: Server returned HTTP response code: 403 for URL: http://172.80.255.65:7000/photo
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
	at sun.net.www.protocol.http.HttpURLConnection$7.run(HttpURLConnection.java:1725)
	at sun.net.www.protocol.http.HttpURLConnection$7.run(HttpURLConnection.java:1723)
	at java.security.AccessController.doPrivileged(Native Method)
	at sun.net.www.protocol.http.HttpURLConnection.getChainedException(HttpURLConnection.java:1721)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1292)
	at com.jameslow.AirPlay.doHTTP(Unknown Source)
	at com.jameslow.AirPlay.doHTTP(Unknown Source)
	at com.jameslow.AirPlay.photoRaw(Unknown Source)
	at com.jameslow.AirPlay.photoRawCompress(Unknown Source)
	at com.jameslow.AirPlay$PhotoThread.run(Unknown Source)
Caused by: java.io.IOException: Server returned HTTP response code: 403 for URL: http://172.80.255.65:7000/photo
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1676)
	at java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:468)
	... 5 more

**Comment by mackowiakp** [comment]
The same here. I think it is becuse the last Apple update to tvOS ver 10.2.2.
My unit is A1625 (32 GB) tvOS ver 10.2.2 (14W756).
Below output from Linux console:
[maciek@Piotr Pobrane]$ java -jar airplay.jar -h apple-tv -a password -d
Press ctrl-c to quit
java.io.IOException: Server returned HTTP response code: 403 for URL: http://apple-tv:7000/photo
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
        at sun.net.www.protocol.http.HttpURLConnection$10.run(HttpURLConnection.java:1926)
        at sun.net.www.protocol.http.HttpURLConnection$10.run(HttpURLConnection.java:1921)
        at java.security.AccessController.doPrivileged(Native Method)
        at sun.net.www.protocol.http.HttpURLConnection.getChainedException(HttpURLConnection.java:1920)
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1490)
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1474)
        at com.jameslow.AirPlay.doHTTP(Unknown Source)
        at com.jameslow.AirPlay.doHTTP(Unknown Source)
        at com.jameslow.AirPlay.photoRaw(Unknown Source)
        at com.jameslow.AirPlay$PhotoThread.run(Unknown Source)
Caused by: java.io.IOException: Server returned HTTP response code: 403 for URL: http://apple-tv:7000/photo
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1876)
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1474)
        at java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:480)
        ... 4 more

**Comment by rafspiny** [comment]
I have the same problem as well. My AppleOs version is 11.
```
raffaele@raffaele-XPS-13-9360:~/Downloads⟫ java -cp "airplay.jar:jmdns.jar" com.jameslow.AirPlay
java.io.IOException: Server returned HTTP response code: 403 for URL: http://mactv:7000/photo
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
        at sun.net.www.protocol.http.HttpURLConnection$10.run(HttpURLConnection.java:1926)
        at sun.net.www.protocol.http.HttpURLConnection$10.run(HttpURLConnection.java:1921)
        at java.security.AccessController.doPrivileged(Native Method)
        at sun.net.www.protocol.http.HttpURLConnection.getChainedException(HttpURLConnection.java:1920)
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1490)
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1474)
        at com.jameslow.AirPlay.doHTTP(Unknown Source)
        at com.jameslow.AirPlay.doHTTP(Unknown Source)
        at com.jameslow.AirPlay.photoRaw(Unknown Source)
        at com.jameslow.AirPlay.photoRawCompress(Unknown Source)
        at com.jameslow.AirPlay$PhotoThread.run(Unknown Source)
Caused by: java.io.IOException: Server returned HTTP response code: 403 for URL: http://mactv:7000/photo
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1876)
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1474)
        at java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:480)
        ... 5 more
```

**Comment by vaibhavebex** [comment]
Any updates on this one?
I am facing the same issue.

**Comment by osilkin98** [comment]
I have this issue too, would be nice if this would be addressed

**Comment by osilkin98** [comment]
I'm surprised that this hasn't been addressed yet but I'm pretty sure this  is related to #15

**Comment by T-vK** [comment]
I just ran into the same issue. Guess this never got fixed?
