### ISSUE TITLE
Dockerfile not working

### ISSUE THREAD

**Issue by PetitCassoulet** [jamesdlow/open-airplay#26]
Doesn't work because the GUI doesn't work with docker, when building the image I get

`debconf: unable to initialize frontend: Dialog
debconf: (TERM is not set, so the dialog frontend is not usable.)
debconf: falling back to frontend: Readline
debconf: unable to initialize frontend: Readline
debconf: (This frontend requires a controlling tty.)
debconf: falling back to frontend: Teletype`

And when launching it :

`java.awt.HeadlessException: 
No X11 DISPLAY variable was set, but this program performed an operation which requires it.
	at java.awt.GraphicsEnvironment.checkHeadless(GraphicsEnvironment.java:207)
	at java.awt.Window.init(Window.java:476)
	at java.awt.Window.<init>(Window.java:438)
	at java.awt.Window.<init>(Window.java:594)
	at java.awt.Dialog.<init>(Dialog.java:665)
	at javax.swing.JDialog.<init>(JDialog.java:590)
	at javax.swing.JDialog.<init>(JDialog.java:552)
	at com.jameslow.AirPlay.searchDialog(Unknown Source)
	at com.jameslow.AirPlay.searchDialog(Unknown Source)
	at com.jameslow.AirPlay.main(Unknown Source)`

**Comment by lhriley** [comment]
@PetitCassoulet I realize this is a little stale, but this worked for me:

```
$ docker build -t open-airplay:local .
$ docker run -e DISPLAY -v $XAUTHORITY:/root/.Xauthority --net=host open-airplay:local
```

I can get the GUI to pop up, but I end up with a 403. I would guess that I need to provide a 4 digit code, but never get prompted for it.

```
java.io.IOException: Server returned HTTP response code: 403 for URL: http://1.2.3.4:7000/photo
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
        at sun.net.www.protocol.http.HttpURLConnection$7.run(HttpURLConnection.java:1743)
        at sun.net.www.protocol.http.HttpURLConnection$7.run(HttpURLConnection.java:1741)
        at java.security.AccessController.doPrivileged(Native Method)
        at sun.net.www.protocol.http.HttpURLConnection.getChainedException(HttpURLConnection.java:1739)
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1310)
        at com.jameslow.AirPlay.doHTTP(Unknown Source)
        at com.jameslow.AirPlay.doHTTP(Unknown Source)
        at com.jameslow.AirPlay.photoRaw(Unknown Source)
        at com.jameslow.AirPlay.photoRawCompress(Unknown Source)
        at com.jameslow.AirPlay$PhotoThread.run(Unknown Source)
Caused by: java.io.IOException: Server returned HTTP response code: 403 for URL: http://1.2.3.4:7000/photo
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1694)
        at java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:468)
        ... 5 more

```
